baseURL: "https://lin-wlx.github.io/"
languageCode: "en-uk"
title: "Linxuan Wang"
theme: "PaperMod"


menu:
  main:
    - identifier: cv
      name: CV
      url: /cv/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: guitar
      name: Guitar
      url: /guitar/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true

